using System.Text.RegularExpressions;

namespace AgriSage.Application.Features.Files;

public sealed record ImageType(string ContentType, string Extension);

// Rules for uploaded product/brand images and delivery photos. The type is decided by the file content (magic bytes), never by the
// client-supplied name or Content-Type.
public static partial class ImageRules
{
    public const long MaxBytes = 3 * 1024 * 1024;

    // Phone photos taken on delivery are larger than catalog images.
    public const long MaxProofBytes = 5 * 1024 * 1024;

    // Farmers photograph leaves with a phone camera, like delivery staff.
    public const long MaxDiagnosisBytes = 5 * 1024 * 1024;

    public static readonly ImageType Jpeg = new("image/jpeg", ".jpg");
    public static readonly ImageType Png = new("image/png", ".png");
    public static readonly ImageType Webp = new("image/webp", ".webp");

    public static ImageType? Detect(ReadOnlySpan<byte> header)
    {
        if (header.Length >= 3 && header[0] == 0xFF && header[1] == 0xD8 && header[2] == 0xFF)
        {
            return Jpeg;
        }

        if (header.Length >= 8 && header[..8].SequenceEqual((byte[])[0x89, 0x50, 0x4E, 0x47, 0x0D, 0x0A, 0x1A, 0x0A]))
        {
            return Png;
        }

        // RIFF....WEBP
        if (header.Length >= 12
            && header[..4].SequenceEqual("RIFF"u8)
            && header[8..12].SequenceEqual("WEBP"u8))
        {
            return Webp;
        }

        return null;
    }

    // The content type of a key generated by the upload (its extension was chosen from the file content).
    public static string? ContentTypeOf(string? key) => key switch
    {
        _ when key is null => null,
        _ when key.EndsWith(Jpeg.Extension, StringComparison.Ordinal) => Jpeg.ContentType,
        _ when key.EndsWith(Png.Extension, StringComparison.Ordinal) => Png.ContentType,
        _ when key.EndsWith(Webp.Extension, StringComparison.Ordinal) => Webp.ContentType,
        _ => null
    };

    // Only keys generated by the upload (folder year/month, 32 hex characters) may be deleted through the API.
    public static bool IsValidKey(string? key) => key is not null && StorageKey().IsMatch(key);

    [GeneratedRegex(@"^\d{4}/\d{2}/[0-9a-f]{32}\.(jpg|png|webp)$")]
    private static partial Regex StorageKey();
}
